# Generated by Django 4.1.7 on 2023-03-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTOPARC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carburant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prise', models.DateTimeField(auto_now_add=True)),
                ('kilometrage_dern_plein', models.IntegerField(blank=True, null=True)),
                ('kilometrage_actu', models.IntegerField(blank=True, null=True)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('cout', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('station', models.CharField(choices=[('TOTAL', 'TOTAL'), ('SHELL', 'SHELL'), ('DHL', 'DHL'), ('PETRO IVOIRE', 'PETRO IVOIRE'), ('IVOIRE WIN', 'IVOIRE WIN')], max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=22)),
                ('prenom', models.CharField(max_length=40)),
                ('date_naissance', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Enregist',
        ),
        migrations.AlterField(
            model_name='projet',
            name='date_fin',
            field=models.DateTimeField(blank=True),
        ),
    ]
