# Generated by Django 4.1.7 on 2023-03-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTOPARC', '0003_rename_date_naissance_person_date_inscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_inscription',
            field=models.DateTimeField(),
        ),
    ]
