# Generated by Django 4.1.7 on 2023-03-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTOPARC', '0004_alter_person_date_inscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=100)),
                ('marque', models.CharField(max_length=100)),
                ('couleur', models.CharField(max_length=100)),
                ('num_serie', models.CharField(max_length=100)),
                ('carburant', models.CharField(max_length=100)),
                ('vehi_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('prix', models.IntegerField(default=0)),
                ('date_achat', models.DateTimeField()),
                ('garentie', models.DateTimeField()),
                ('vehi_enregistre_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
