# Generated by Django 4.1.5 on 2023-03-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTOPARC', '0005_vehicule_delete_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='vehi_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
