# Generated by Django 4.1.5 on 2023-03-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTOPARC', '0006_alter_vehicule_vehi_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='vehi_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
