# Generated by Django 4.1.7 on 2023-03-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTOPARC', '0008_marque'),
    ]

    operations = [
        migrations.AddField(
            model_name='marque',
            name='logo',
            field=models.ImageField(default='1', upload_to='marques/'),
            preserve_default=False,
        ),
    ]
