# Generated by Django 4.1.7 on 2023-03-29 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AUTOPARC', '0009_marque_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marque',
            name='logo',
        ),
    ]
