# Generated by Django 4.1.7 on 2023-03-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTOPARC', '0010_remove_marque_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='marque',
            name='logo',
            field=models.ImageField(default='1', upload_to='marques/'),
            preserve_default=False,
        ),
    ]
