# Generated by Django 4.1.7 on 2023-03-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTOPARC', '0011_marque_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marque',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='marques/'),
        ),
    ]
